# Generated by Django 5.1.4 on 2025-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comdepart', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=32, null=True, verbose_name='标题'),
        ),
    ]
