# Generated by Django 5.1.4 on 2025-01-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comdepart', '0005_userinfo_depart_id_alter_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='depart_id',
            new_name='depart',
        ),
    ]
