# Generated by Django 5.1.5 on 2025-01-21 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comdepart', '0007_remove_userinfo_depart_userinfo_depart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comdepart.department', verbose_name='部门ID'),
        ),
    ]
