# Generated by Django 5.1.5 on 2025-01-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comdepart', '0008_alter_department_id_alter_userinfo_depart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
