# Generated by Django 5.1.5 on 2025-01-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comdepart', '0009_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comdepart.department', verbose_name='部门ID'),
        ),
    ]
